name: Semgrep Security Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  semgrep_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: './repo'

      # Restaurar paquetes NuGet
      - name: Restore NuGet packages
        run: nuget restore ./repo/Proyecto_RUMI/Proyecto_Web2_Aguilar_Chino_Gonzales_Perez.sln

      # Semgrep Analysis usando Docker
      - name: Set up Semgrep using Docker
        run: docker pull semgrep/semgrep

      - name: Run Semgrep scan
        run: docker run --rm -v $(pwd):/src semgrep/semgrep semgrep scan --config="p/default" --json --output semgrep.json --metrics=off

      # Instalar prospector-html para generar reporte HTML de Semgrep
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install prospector-html
        run: python -m pip install prospector2html

      # Convertir los resultados de Semgrep a HTML
      - name: Convert Semgrep results to HTML
        run: prospector-html --input semgrep.json --output semgrep-report.html --filter semgrep || true

      # Subir el reporte de Semgrep como artefacto
      - name: Upload Semgrep report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-report
          path: semgrep-report.html

