name: Snyk Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  snyk:
    name: Snyk Vulnerability Analysis
    runs-on: windows-latest

    steps:
      # Paso 1: Habilitar rutas largas en Git
      - name: Enable long paths in Git
        run: git config --system core.longpaths true

      # Paso 2: Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v4  # Actualizado a v4

      # Paso 3: Instalar MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2  # Actualizado a v2

      # Paso 4: Restaurar paquetes NuGet
      - name: Restore NuGet packages
        run: nuget restore ./Proyecto_Web2_Aguilar_Chino_Gonzales_Perez/Proyecto_Web2_Aguilar_Chino_Gonzales_Perez.sln

      # Paso 5: Instalar la CLI de Snyk
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Paso 6: Ejecutar escaneo de Snyk para verificar vulnerabilidades usando el archivo packages.config
      - name: Run Snyk to check for vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --severity-threshold=high --sarif-file-output=snyk.sarif --file=./Proyecto_Web2_Aguilar_Chino_Gonzales_Perez/packages.config

      # Paso 7: Generar reporte HTML a partir del archivo SARIF
      - name: Generate HTML report from SARIF
        run: |
          echo "<!DOCTYPE html>
          <html lang='es'>
          <head>
              <meta charset='UTF-8'>
              <meta name='viewport' content='width=device-width, initial-scale=1.0'>
              <title>Resultados de Vulnerabilidades</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 20px; }
                  table { width: 100%; border-collapse: collapse; }
                  th, td { border: 1px solid #ddd; padding: 8px; }
                  th { background-color: #f2f2f2; }
              </style>
          </head>
          <body>
              <h1>Resultados de Vulnerabilidades</h1>
              <table>
                  <thead>
                      <tr>
                          <th>Regla ID</th>
                          <th>Nivel</th>
                          <th>Mensaje</th>
                          <th>Ubicación</th>
                      </tr>
                  </thead>
                  <tbody>" > snyk_report.html

          # Procesar el archivo SARIF y generar el HTML
          cat snyk.sarif | jq -r '.runs[].results[] | "<tr><td>\(.ruleId)</td><td>\(.level)</td><td>\(.message.text)</td><td>\(.locations[0].physicalLocation.artifactLocation.uri // "N/A") (Línea \(.locations[0].physicalLocation.region.startLine // "N/A"))</td></tr>"' >> snyk_report.html

          echo "</tbody></table></body></html>" >> snyk_report.html

      # Paso 8: Subir el reporte HTML como artefacto
      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v4  # Actualizado a v4
        with:
          name: snyk-report
          path: snyk_report.html

