name: Snyk Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  snyk:
    name: Snyk Vulnerability Analysis
    runs-on: windows-latest

    steps:
      # Paso para clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: './repo'

      # Restaurar paquetes NuGet para .NET Framework 4.8
      - name: Restore NuGet packages
        run: nuget restore ./repo/Proyecto_RUMI/Proyecto_Web2_Aguilar_Chino_Gonzales_Perez.sln

      # Configurar .NET Framework 4.8
      - name: Set up .NET version
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '4.8.x'

      # Instalar Snyk y snyk-to-html
      - name: Install Snyk and snyk-to-html
        run: |
          npm install -g snyk snyk-to-html

      # Ejecutar escaneo de Snyk para verificar vulnerabilidades en el código
      - name: Run Snyk to check for vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk code test --json | snyk-to-html -o snyk-report.html

      # Subir el reporte HTML como artefacto
      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: snyk-report
          path: snyk-report.html

